spring:
  datasource:
    url: jdbc:mysql://localhost:3306/neuromentor?useSSL=false&serverTimezone=UTC
    username: root
    password: Vitor@0228
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
